name: platform
services:
  database:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: platform_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - '50000:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - platformnet
    restart: unless-stopped
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: gresau/localstack-persist:3
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/data:/persisted-data"
    networks:
      - platformnet
    restart: unless-stopped
  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - platformnet
    restart: unless-stopped
networks:
  platformnet:
    driver: bridge
volumes:
  db_data:
  localstack: